# Generated by Django 3.1.5 on 2021-02-10 06:55

import blog.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('author', models.CharField(blank=True, max_length=60)),
                ('main_text', models.TextField(blank=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='paper',
            name='attachment',
        ),
        migrations.AddField(
            model_name='paper',
            name='pdf',
            field=models.FileField(null=True, upload_to=blog.models.content_file_name),
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.AddField(
            model_name='post',
            name='references',
            field=models.ManyToManyField(related_name='contained_posts', to='blog.Paper'),
        ),
    ]
