# Generated by Django 3.1.5 on 2021-02-10 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210210_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='pdf',
            new_name='attachment',
        ),
    ]
