# Generated by Django 3.1.5 on 2021-02-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210210_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='references',
        ),
        migrations.AddField(
            model_name='post',
            name='reference',
            field=models.ManyToManyField(related_name='contained_post', to='blog.Paper'),
        ),
    ]
