# Generated by Django 3.1.5 on 2021-02-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210210_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='journal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paper',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
