# Generated by Django 3.1.5 on 2021-02-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210210_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
    ]
