# Generated by Django 3.1.5 on 2021-02-22 02:40

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210210_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.content_file_name),
        ),
    ]
