# Generated by Django 3.1.5 on 2021-02-22 05:45

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210222_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='attachment',
            field=models.FileField(null=True, upload_to=blog.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='post',
            name='reference',
            field=models.ManyToManyField(null=True, related_name='contained_post', to='blog.Paper'),
        ),
    ]
