# Generated by Django 3.1.5 on 2021-02-22 05:47

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210222_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='attachment',
            field=models.FileField(blank=True, default='null', upload_to=blog.models.content_file_name),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='reference',
            field=models.ManyToManyField(blank=True, related_name='contained_post', to='blog.Paper'),
        ),
    ]
